heat_template_version: 2014-10-16
description: 'Extra Pre-Deployment Config, multiple'
parameters:
  server:
    type: string

resources:

  ContrailInjectCert:
    type: tls-cert-inject-contrail.yaml
    properties:
        server: {get_param: server}

  # Note depends_on may be used for serialization if ordering is important
  ContrailSetCertPath:
    type: set-cert-path.yaml
    properties:
        server: {get_param: server}
