heat_template_version: 2015-04-30

description: >
  This is a template which will build the TLS Certificates necessary
  for the load balancer using the given parameters.

parameters:
  # Can be overridden by parameter_defaults if the user wants to try deploying
  # this in a distro that doesn't support this path.
  DeployedSSLCertificatePath:
    default: '/etc/pki/tls/private/overcloud_endpoint.pem'
    description: >
        The filepath of the certificate as it will be stored in the controller.
    type: string

  # Passed in by the controller
  server:
    description: ID of the controller node to apply this config to
    type: string

resources:

  ContrailTLSPathConfig:
    type: OS::Heat::StructuredConfig
    properties:
      group: os-apply-config
      config:
        hiera:
          merge_behavior: deeper
          datafiles:
            extraconfig:
              mapped_data: # data supplied directly to this deployment configuration, etc
                contrail::service_certificate: {get_param: DeployedSSLCertificatePath}

  ContrailTLSPathDeployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      name: ContrailTLSPathDeployment
      config: {get_resource: ContrailTLSPathConfig}
      server: {get_param: server}
