heat_template_version: 2016-10-14

description: >
  Contrail Analytics node configured by Puppet.

parameters:
  ContrailTsnExtraConfig:
    default: {}
    description: |
      ContrailTsn specific hiera configuration data to inject into the cluster.
    type: json
  ContrailTsnIPs:
    default: {}
    description: >
      A network mapped list of IPs to assign to ContrailTsns in the following form:
      {
        "internal_api": ["a.b.c.d", "e.f.g.h"],
        ...
      }
    type: json
  Debug:
    default: ''
    description: Set to True to enable debugging on all services.
    type: string
  EnableLoadBalancer:
    default: true
    description: Whether to deploy a LoadBalancer on the ContrailTsn
    type: boolean
  ExtraConfig:
    default: {}
    description: |
      Additional hieradata to inject into the cluster, note that
      ContrailTsnExtraConfig takes precedence over ExtraConfig.
    type: json
  OvercloudContrailTsnFlavor:
    description: Flavor for control nodes to request when deploying.
    default: baremetal
    type: string
    constraints:
      - custom_constraint: nova.flavor
  ContrailTsnImage:
    type: string
    default: overcloud-full
    constraints:
      - custom_constraint: glance.image
  ImageUpdatePolicy:
    default: 'REBUILD_PRESERVE_EPHEMERAL'
    description: What policy to use when reconstructing instances. REBUILD for rebuilds, REBUILD_PRESERVE_EPHEMERAL to preserve /mnt.
    type: string
  KeyName:
    default: default
    description: Name of an existing Nova key pair to enable SSH access to the instances
    type: string
    constraints:
      - custom_constraint: nova.keypair
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  UpdateIdentifier:
    default: ''
    type: string
    description: >
      Setting to a previously unused value during stack-update will trigger
      package update on all nodes
  Hostname:
    type: string
    default: '' # Defaults to Heat created hostname
  HostnameMap:
    type: json
    default: {}
    description: Optional mapping to override hostnames
  NetworkDeploymentActions:
    type: comma_delimited_list
    description: >
      Heat action when to apply network configuration changes
    default: ['CREATE']
  NodeIndex:
    type: number
    default: 0
  SoftwareConfigTransport:
    default: POLL_SERVER_CFN
    description: |
      How the server should receive the metadata required for software configuration.
    type: string
    constraints:
    - allowed_values: [POLL_SERVER_CFN, POLL_SERVER_HEAT, POLL_TEMP_URL, ZAQAR_MESSAGE]
  CloudDomain:
    default: 'localdomain'
    type: string
    description: >
      The DNS domain used for the hosts. This should match the dhcp_domain
      configured in the Undercloud neutron. Defaults to localdomain.
  ServerMetadata:
    default: {}
    description: >
      Extra properties or metadata passed to Nova for the created nodes in
    type: json
  ContrailTsnSchedulerHints:
    type: json
    description: Optional scheduler hints to pass to nova
    default: {}
  ServiceConfigSettings:
    type: json
    default: {}
  ServiceNames:
    type: comma_delimited_list
    default: []
  MonitoringSubscriptions:
    type: comma_delimited_list
    default: []
  ConfigCommand:
    type: string
    description: Command which will be run whenever configuration data changes
    default: os-refresh-config --timeout 14400

resources:

  ContrailTsn:
    type: OS::TripleO::Server
    metadata:
      os-collect-config:
        command: {get_param: ConfigCommand}
    properties:
      image: {get_param: ContrailTsnImage}
      image_update_policy: {get_param: ImageUpdatePolicy}
      flavor: {get_param: OvercloudContrailTsnFlavor}
      key_name: {get_param: KeyName}
      networks:
        - network: ctlplane
      user_data_format: SOFTWARE_CONFIG
      user_data: {get_resource: UserData}
      name:
        str_replace:
            template: {get_param: Hostname}
            params: {get_param: HostnameMap}
      software_config_transport: {get_param: SoftwareConfigTransport}
      metadata: {get_param: ServerMetadata}
      scheduler_hints: {get_param: ContrailTsnSchedulerHints}

  # Combine the NodeAdminUserData and NodeUserData mime archives
  UserData:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: NodeAdminUserData}
        type: multipart
      - config: {get_resource: NodeUserData}
        type: multipart

  # Creates the "heat-admin" user if configured via the environment
  # Should return a OS::Heat::MultipartMime reference via OS::stack_id
  NodeAdminUserData:
    type: OS::TripleO::NodeAdminUserData

  # For optional operator additional userdata
  # Should return a OS::Heat::MultipartMime reference via OS::stack_id
  NodeUserData:
    type: OS::TripleO::NodeUserData

  ExternalPort:
    type: OS::TripleO::ContrailTsn::Ports::ExternalPort
    properties:
      IPPool: {get_param: ContrailTsnIPs}
      NodeIndex: {get_param: NodeIndex}
      ControlPlaneIP: {get_attr: [ContrailTsn, networks, ctlplane, 0]}

  InternalApiPort:
    type: OS::TripleO::ContrailTsn::Ports::InternalApiPort
    properties:
      IPPool: {get_param: ContrailTsnIPs}
      NodeIndex: {get_param: NodeIndex}
      ControlPlaneIP: {get_attr: [ContrailTsn, networks, ctlplane, 0]}

  StoragePort:
    type: OS::TripleO::ContrailTsn::Ports::StoragePort
    properties:
      IPPool: {get_param: ContrailTsnIPs}
      NodeIndex: {get_param: NodeIndex}
      ControlPlaneIP: {get_attr: [ContrailTsn, networks, ctlplane, 0]}

  StorageMgmtPort:
    type: OS::TripleO::ContrailTsn::Ports::StorageMgmtPort
    properties:
      IPPool: {get_param: ContrailTsnIPs}
      NodeIndex: {get_param: NodeIndex}
      ControlPlaneIP: {get_attr: [ContrailTsn, networks, ctlplane, 0]}

  TenantPort:
    type: OS::TripleO::ContrailTsn::Ports::TenantPort
    properties:
      IPPool: {get_param: ContrailTsnIPs}
      NodeIndex: {get_param: NodeIndex}
      ControlPlaneIP: {get_attr: [ContrailTsn, networks, ctlplane, 0]}

  ManagementPort:
    type: OS::TripleO::ContrailTsn::Ports::ManagementPort
    properties:
      IPPool: {get_param: ContrailTsnIPs}
      NodeIndex: {get_param: NodeIndex}
      ControlPlaneIP: {get_attr: [ContrailTsn, networks, ctlplane, 0]}

  NetIpMap:
    type: OS::TripleO::Network::Ports::NetIpMap
    properties:
      ControlPlaneIp: {get_attr: [ContrailTsn, networks, ctlplane, 0]}
      ExternalIp: {get_attr: [ExternalPort, ip_address]}
      ExternalIpSubnet: {get_attr: [ExternalPort, ip_subnet]}
      ExternalIpUri: {get_attr: [ExternalPort, ip_address_uri]}
      InternalApiIp: {get_attr: [InternalApiPort, ip_address]}
      InternalApiIpSubnet: {get_attr: [InternalApiPort, ip_subnet]}
      InternalApiIpUri: {get_attr: [InternalApiPort, ip_address_uri]}
      StorageIp: {get_attr: [StoragePort, ip_address]}
      StorageIpSubnet: {get_attr: [StoragePort, ip_subnet]}
      StorageIpUri: {get_attr: [StoragePort, ip_address_uri]}
      StorageMgmtIp: {get_attr: [StorageMgmtPort, ip_address]}
      StorageMgmtIpSubnet: {get_attr: [StorageMgmtPort, ip_subnet]}
      StorageMgmtIpUri: {get_attr: [StorageMgmtPort, ip_address_uri]}
      TenantIp: {get_attr: [TenantPort, ip_address]}
      TenantIpSubnet: {get_attr: [TenantPort, ip_subnet]}
      TenantIpUri: {get_attr: [TenantPort, ip_address_uri]}
      ManagementIp: {get_attr: [ManagementPort, ip_address]}
      ManagementIpSubnet: {get_attr: [ManagementPort, ip_subnet]}
      ManagementIpUri: {get_attr: [ManagementPort, ip_address_uri]}

  NetworkConfig:
    type: OS::TripleO::ContrailTsn::Net::SoftwareConfig
    properties:
      ControlPlaneIp: {get_attr: [ContrailTsn, networks, ctlplane, 0]}
      ExternalIpSubnet: {get_attr: [ExternalPort, ip_subnet]}
      InternalApiIpSubnet: {get_attr: [InternalApiPort, ip_subnet]}
      StorageIpSubnet: {get_attr: [StoragePort, ip_subnet]}
      StorageMgmtIpSubnet: {get_attr: [StorageMgmtPort, ip_subnet]}
      TenantIpSubnet: {get_attr: [TenantPort, ip_subnet]}
      ManagementIpSubnet: {get_attr: [ManagementPort, ip_subnet]}

  NetworkDeployment:
    type: OS::TripleO::SoftwareDeployment
    properties:
      name: NetworkDeployment
      config: {get_resource: NetworkConfig}
      server: {get_resource: ContrailTsn}
      actions: {get_param: NetworkDeploymentActions}

  # Resource for site-specific injection of root certificate
  NodeTLSCAData:
    depends_on: NetworkDeployment
    type: OS::TripleO::NodeTLSCAData
    properties:
      server: {get_resource: ContrailTsn}

  # Resource for site-specific passing of private keys/certificates
  NodeTLSDataContrail:
    depends_on: NodeTLSCAData
    type: OS::TripleO::NodeTLSDataContrail
    properties:
      server: {get_resource: ContrailTsn}
      NodeIndex: {get_param: NodeIndex}


  ContrailTsnDeployment:
    type: OS::TripleO::SoftwareDeployment
    depends_on: NetworkDeployment
    properties:
      name: ContrailTsnDeployment
      config: {get_resource: ContrailTsnConfig}
      server: {get_resource: ContrailTsn}
      input_values:
        bootstack_nodeid: {get_attr: [ContrailTsn, name]}

  # Map heat metadata into hiera datafiles
  ContrailTsnConfig:
    type: OS::Heat::StructuredConfig
    properties:
      group: os-apply-config
      config:
        hiera:
          hierarchy:
            - '"%{::uuid}"'
            - heat_config_%{::deploy_config_name}
            - contrail_tsn_extraconfig
            - extraconfig
            - service_configs
            - service_names
            - contrail_tsn
            - bootstrap_node # provided by BootstrapNodeConfig
            - all_nodes # provided by allNodesConfig
            - vip_data # provided by allNodesConfig
            - '"%{::osfamily}"'
          merge_behavior: deeper
          datafiles:
            service_names:
              mapped_data:
                service_names: {get_param: ServiceNames}
                sensu::subscriptions: {get_param: MonitoringSubscriptions}
            service_configs:
              mapped_data:
                map_replace:
                  - {get_param: ServiceConfigSettings}
                  - values: {get_attr: [NetIpMap, net_ip_map]}
            contrail_tsn_extraconfig:
              mapped_data:
                map_merge:
                  - {get_param: ContrailTsnExtraConfig}
            extraconfig:
              mapped_data: {get_param: ExtraConfig}
            contrail_tsn:
              mapped_data: # data supplied directly to this deployment configuration, etc
                bootstack_nodeid: {get_input: bootstack_nodeid}
                contrail::tsn::service_certificate: {get_attr: [NodeTLSDataContrail, deployed_ssl_certificate_path]}

  # Hook for site-specific additional pre-deployment config, e.g extra hieradata
  ContrailTsnExtraConfigPre:
    depends_on: ContrailTsnDeployment
    type: OS::TripleO::ContrailTsnExtraConfigPre
    properties:
        server: {get_resource: ContrailTsn}

  # Hook for site-specific additional pre-deployment config,
  # applying to all nodes, e.g node registration/unregistration
  NodeExtraConfig:
    depends_on: [ContrailTsnExtraConfigPre, NodeTLSDataContrail]
    type: OS::TripleO::NodeExtraConfig
    properties:
        server: {get_resource: ContrailTsn}

  UpdateConfig:
    type: OS::TripleO::Tasks::PackageUpdate

  UpdateDeployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      name: UpdateDeployment
      config: {get_resource: UpdateConfig}
      server: {get_resource: ContrailTsn}
      input_values:
        update_identifier:
          get_param: UpdateIdentifier

outputs:
  ip_address:
    description: IP address of the server in the ctlplane network
    value: {get_attr: [ContrailTsn, networks, ctlplane, 0]}
  external_ip_address:
    description: IP address of the server in the external network
    value: {get_attr: [ExternalPort, ip_address]}
  internal_api_ip_address:
    description: IP address of the server in the internal_api network
    value: {get_attr: [InternalApiPort, ip_address]}
  storage_ip_address:
    description: IP address of the server in the storage network
    value: {get_attr: [StoragePort, ip_address]}
  storage_mgmt_ip_address:
    description: IP address of the server in the storage_mgmt network
    value: {get_attr: [StorageMgmtPort, ip_address]}
  tenant_ip_address:
    description: IP address of the server in the tenant network
    value: {get_attr: [TenantPort, ip_address]}
  management_ip_address:
    description: IP address of the server in the management network
    value: {get_attr: [ManagementPort, ip_address]}
  hostname:
    description: Hostname of the server
    value: {get_attr: [ContrailTsn, name]}
  hostname_map:
    description: Mapping of network names to hostnames
    value:
      external:
        list_join:
        - '.'
        - - {get_attr: [ContrailTsn, name]}
          - external
          - {get_param: CloudDomain}
      internal_api:
        list_join:
        - '.'
        - - {get_attr: [ContrailTsn, name]}
          - internalapi
          - {get_param: CloudDomain}
      storage:
        list_join:
        - '.'
        - - {get_attr: [ContrailTsn, name]}
          - storage
          - {get_param: CloudDomain}
      storage_mgmt:
        list_join:
        - '.'
        - - {get_attr: [ContrailTsn, name]}
          - storagemgmt
          - {get_param: CloudDomain}
      tenant:
        list_join:
        - '.'
        - - {get_attr: [ContrailTsn, name]}
          - tenant
          - {get_param: CloudDomain}
      management:
        list_join:
        - '.'
        - - {get_attr: [ContrailTsn, name]}
          - management
          - {get_param: CloudDomain}
      ctlplane:
        list_join:
        - '.'
        - - {get_attr: [ContrailTsn, name]}
          - ctlplane
          - {get_param: CloudDomain}
  hosts_entry:
    description: >
      Server's IP address and hostname in the /etc/hosts format
    value:
      str_replace:
        template: |
          PRIMARYIP PRIMARYHOST.DOMAIN PRIMARYHOST
          EXTERNALIP EXTERNALHOST.DOMAIN EXTERNALHOST
          INTERNAL_APIIP INTERNAL_APIHOST.DOMAIN INTERNAL_APIHOST
          STORAGEIP STORAGEHOST.DOMAIN STORAGEHOST
          STORAGE_MGMTIP STORAGE_MGMTHOST.DOMAIN STORAGE_MGMTHOST
          TENANTIP TENANTHOST.DOMAIN TENANTHOST
          MANAGEMENTIP MANAGEMENTHOST.DOMAIN MANAGEMENTHOST
          CTLPLANEIP CTLPLANEHOST.DOMAIN CTLPLANEHOST
        params:
          PRIMARYIP: {get_attr: [NetIpMap, net_ip_map, {get_param: [ServiceNetMap, ContrailTsnHostnameResolveNetwork]}]}
          DOMAIN: {get_param: CloudDomain}
          PRIMARYHOST: {get_attr: [ContrailTsn, name]}
          EXTERNALIP: {get_attr: [ExternalPort, ip_address]}
          EXTERNALHOST:
            list_join:
            - '.'
            - - {get_attr: [ContrailTsn, name]}
              - external
          INTERNAL_APIIP: {get_attr: [InternalApiPort, ip_address]}
          INTERNAL_APIHOST:
            list_join:
            - '.'
            - - {get_attr: [ContrailTsn, name]}
              - internalapi
          STORAGEIP: {get_attr: [StoragePort, ip_address]}
          STORAGEHOST:
            list_join:
            - '.'
            - - {get_attr: [ContrailTsn, name]}
              - storage
          STORAGE_MGMTIP: {get_attr: [StorageMgmtPort, ip_address]}
          STORAGE_MGMTHOST:
            list_join:
            - '.'
            - - {get_attr: [ContrailTsn, name]}
              - storagemgmt
          TENANTIP: {get_attr: [TenantPort, ip_address]}
          TENANTHOST:
            list_join:
            - '.'
            - - {get_attr: [ContrailTsn, name]}
              - tenant
          MANAGEMENTIP: {get_attr: [ManagementPort, ip_address]}
          MANAGEMENTHOST:
            list_join:
            - '.'
            - - {get_attr: [ContrailTsn, name]}
              - management
          CTLPLANEIP: {get_attr: [ContrailTsn, networks, ctlplane, 0]}
          CTLPLANEHOST:
            list_join:
            - '.'
            - - {get_attr: [ContrailTsn, name]}
              - ctlplane
  nova_server_resource:
    description: Heat resource handle for the Nova compute server
    value:
      {get_resource: ContrailTsn}
  tls_key_modulus_md5:
    description: MD5 checksum of the TLS Key Modulus
    value: {get_attr: [NodeTLSDataContrail, key_modulus_md5]}
  tls_cert_modulus_md5:
    description: MD5 checksum of the TLS Certificate Modulus
    value: {get_attr: [NodeTLSDataContrail, cert_modulus_md5]}
