heat_template_version: 2014-10-16

# NOTE: You don't need to pass the parameter explicitly from the
# parent template, it can be specified via the parameter_defaults
# in the resource_registry instead, if you want to override the default
# and/or share values with other templates in the tree.
parameters:
  repo_url:
    type: string
    default: http://192.0.2.1/contrail-3.2.0.0-19

description: >
  This is an example showing how you can do firstboot configuration
  of the nodes via cloud-init.  To enable this, replace the default
  mapping of OS::TripleO::NodeUserData in ../overcloud_resource_registry*

resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: vrouter_module_config}

  vrouter_module_config:
    type: OS::Heat::SoftwareConfig
    properties:
      config:
        str_replace:
          template: |
            #!/bin/bash
            if [ `hostname |awk -F"-" '{print $2}'` == "novacompute" ]; then 
              cat <<EOF > /etc/yum.repos.d/contrail.repo
            [Contrail]
            baseurl=$repo_url
            enabled=1
            gpgcheck=0
            protect=1
            EOF
              yum install -y contrail-vrouter
              yum install -y contrail-vrouter-init
              weak-modules --add-kernel
              modprobe vrouter
              echo "I was here" > /tmp/bla
            fi
          params:
            $repo_url: {get_param: repo_url}

outputs:
  # This means get_resource from the parent template will get the userdata, see:
  # http://docs.openstack.org/developer/heat/template_guide/composition.html#making-your-template-resource-more-transparent
  # Note this is new-for-kilo, an alternative is returning a value then using
  # get_attr in the parent template instead.
  OS::stack_id:
    value: {get_resource: userdata}
